flowchart TB

subgraph Root
  subgraph Management A
    subgraph Management A/A
      drone_02["Drone"]
    end
    subgraph Management A/B
      drone_03["Drone"]
      drone_04["Drone"]
      drone_05["Drone"]
    end
    drone_01["Drone"]
    drone_19["Drone"]
    drone_20["Drone"]
    drone_21["Drone"]
    drone_22["Drone"]
    drone_23["Drone"]
    drone_24["Drone"]
  end
  subgraph Management B
    subgraph Management B/A
      subgraph Management B/A/B
        drone_31["Drone"]
        drone_32["Drone"]
        drone_33["Drone"]
        drone_34["Drone"]
        drone_35["Drone"]
        drone_36["Drone"]
      end
      drone_06["Drone"]
      drone_07["Drone"]
      drone_08["Drone"]
      drone_09["Drone"]
      drone_10["Drone"]
      drone_11["Drone"]
      drone_12["Drone"]
    end
    subgraph Management B/B
      subgraph Management B/B/A
        drone_37["Drone"]
        drone_38["Drone"]
        drone_39["Drone"]
        drone_40["Drone"]
      end
      drone_13["Drone"]
      drone_14["Drone"]
      drone_15["Drone"]
      drone_16["Drone"]
      drone_17["Drone"]
      drone_18["Drone"]
    end
    drone_25["Drone"]
    drone_26["Drone"]
    drone_27["Drone"]
    drone_28["Drone"]
    drone_29["Drone"]
    drone_30["Drone"]
  end
end



