@startuml

hide stereotype
title Reference Model

top to bottom direction

<style>
    .drone {
        BackgroundColor #002a41;
        BorderColor #dddddd;
        FontColor #ffffff;
    }
    .drone2 {
        BackgroundColor #224558;
        BorderColor #dddddd;
        FontColor #ffffff;
    }
    .global {
        BackgroundColor #426070;
        BorderColor #dddddd;
        FontColor #ffffff;
    }
    .mgmt {
        BackgroundColor #8194a0;
        BorderColor #dddddd;
        FontColor #ffffff;
    }
</style>

rectangle "Root" as root <<global>> {
  rectangle "Management A" as mgmt_a <<mgmt>> {
    rectangle "Management A/A" as mgmt_a_a <<mgmt>> {
      rectangle "Drone" as drone_02 <<drone>> 
    }
    rectangle "Management A/B" as mgmt_a_b <<mgmt>> {
      rectangle "Drone" as drone_03 <<drone>> 
      rectangle "Drone" as drone_04 <<drone>> 
      rectangle "Drone" as drone_05 <<drone>> 
    }
    rectangle "Drone" as drone_01 <<drone>> 
    rectangle "Drone" as drone_19 <<drone>> 
    rectangle "Drone" as drone_20 <<drone>> 
    rectangle "Drone" as drone_21 <<drone>> 
    rectangle "Drone" as drone_22 <<drone>> 
    rectangle "Drone" as drone_23 <<drone>> 
    rectangle "Drone" as drone_24 <<drone>> 
  }
  rectangle "Management B" as mgmt_b <<mgmt>> {
    rectangle "Management B/A" as mgmt_b_a <<mgmt>> {
      rectangle "Management B/A/B" as mgmt_b_a_b <<mgmt>> {
        rectangle "Drone" as drone_31 <<drone>> 
        rectangle "Drone" as drone_32 <<drone>> 
        rectangle "Drone" as drone_33 <<drone>> 
        rectangle "Drone" as drone_34 <<drone>> 
        rectangle "Drone" as drone_35 <<drone>> 
        rectangle "Drone" as drone_36 <<drone>> 
      }
      rectangle "Drone" as drone_06 <<drone>> 
      rectangle "Drone" as drone_07 <<drone>> 
      rectangle "Drone" as drone_08 <<drone>> 
      rectangle "Drone" as drone_09 <<drone>> 
      rectangle "Drone" as drone_10 <<drone>> 
      rectangle "Drone" as drone_11 <<drone>> 
      rectangle "Drone" as drone_12 <<drone>> 
    }
    rectangle "Management B/B" as mgmt_b_b <<mgmt>> {
      rectangle "Management B/B/A" as mgmt_b_b_a <<mgmt>> {
        rectangle "Drone" as drone_37 <<drone>> 
        rectangle "Drone" as drone_38 <<drone>> 
        rectangle "Drone" as drone_39 <<drone>> 
        rectangle "Drone" as drone_40 <<drone>> 
      }
      rectangle "Drone" as drone_13 <<drone>> 
      rectangle "Drone" as drone_14 <<drone>> 
      rectangle "Drone" as drone_15 <<drone>> 
      rectangle "Drone" as drone_16 <<drone>> 
      rectangle "Drone" as drone_17 <<drone>> 
      rectangle "Drone" as drone_18 <<drone>> 
    }
    rectangle "Drone" as drone_25 <<drone>> 
    rectangle "Drone" as drone_26 <<drone>> 
    rectangle "Drone" as drone_27 <<drone>> 
    rectangle "Drone" as drone_28 <<drone>> 
    rectangle "Drone" as drone_29 <<drone>> 
    rectangle "Drone" as drone_30 <<drone>> 
  }
}


 drone_03 --> drone_09 : "link"
 drone_03 --> drone_31 : "link"
 drone_04 --> drone_35 : "link"
 drone_05 --> drone_17 : "link"
 drone_05 --> drone_28 : "link"
 drone_05 --> drone_30 : "link"
 drone_06 --> drone_02 : "link"
 drone_06 --> drone_03 : "link"
 drone_06 --> drone_35 : "link"
 drone_09 --> drone_02 : "link"
 drone_09 --> drone_10 : "link"
 drone_10 --> drone_38 : "link"
 drone_11 --> drone_09 : "link"
 drone_13 --> drone_24 : "link"
 drone_14 --> drone_39 : "link"
 drone_15 --> drone_07 : "link"
 drone_15 --> drone_23 : "link"
 drone_17 --> drone_10 : "link"
 drone_17 --> drone_24 : "link"
 drone_18 --> drone_17 : "link"
 drone_18 --> drone_21 : "link"
 drone_18 --> drone_22 : "link"
 drone_19 --> drone_15 : "link"
 drone_23 --> drone_15 : "link"
 drone_23 --> drone_25 : "link"
 drone_25 --> drone_24 : "link"
 drone_26 --> drone_13 : "link"
 drone_26 --> drone_21 : "link"
 drone_26 --> drone_32 : "link"
 drone_27 --> drone_06 : "link"
 drone_28 --> drone_40 : "link"
 drone_29 --> drone_23 : "link"
 drone_29 --> drone_26 : "link"
 drone_30 --> drone_25 : "link"
 drone_31 --> drone_12 : "link"
 drone_31 --> drone_33 : "link"
 drone_32 --> drone_02 : "link"
 drone_32 --> drone_33 : "link"
 drone_35 --> drone_30 : "link"
 drone_36 --> drone_19 : "link"
 drone_37 --> drone_02 : "link"
 drone_37 --> drone_12 : "link"
 drone_38 --> drone_16 : "link"
 drone_38 --> drone_36 : "link"
 drone_40 --> drone_19 : "link"
 drone_40 --> drone_33 : "link"
 drone_40 --> drone_38 : "link"

@enduml
