import:
  profiles:
    - filename: "data.csv"
      tablename: "table1"
      transformations:
        - !AddSQLColumn
          - "repo_id"
          - "SELECT repo_1, repo_2, repo_1 || '-' || repo_2 AS repo_id FROM df"

create:
  steps:
    - !JsCreateEdgesFromRow
        - 

export:
  profiles:
    - filename: "output.gml"
      exporter: "GML"
    - filename: "output.dot"
      exporter: "DOT"
    - filename: "nodes-full.csv"
      exporter: "CSVNodes"
    - filename: "edges-full.csv"
      exporter: "CSVEdges"
