on:
  release:
    types: [created]

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          - os-name: linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl

          - os-name: windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          # - os-name: macos-x86_64
          #   runs-on: macOS-latest
          #   target: x86_64-apple-darwin

          - os-name: macos-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: layercake
          target: ${{ matrix.platform.target }}
          changes-file: "CHANGES.md"
          archive-name: "layercake-${{ github.event.release.tag_name }}-${{ matrix.platform.os-name }}"
