name: Cross-compile Rust Binary

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install cross
        run: |
          cargo install cross

      - name: Cross-compile for x86_64-unknown-linux-musl
        run: |
          cross build --target x86_64-unknown-linux-musl --release

      - name: Cross-compile for x86_64-pc-windows-gnu
        run: |
          cross build --target x86_64-pc-windows-gnu --release

      - name: Cross-compile for aarch64-apple-darwin
        run: |
          cross build --target aarch64-apple-darwin --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: target/x86_64-unknown-linux-musl/release/
          path: target/x86_64-pc-windows-gnu/release/
          path: target/aarch64-apple-darwin/release/
